In [19]:
import pandas as pd
import numpy as np

In [20]:
SimpleData = pd.read_csv('./split2/1_train.csv')

D:\software\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (41) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [21]:
SimpleData.head(5)

,Unnamed: 0,Unnamed: 0.1,ACCEXCCOUNT,ACCRUNTIMES,ACCSTATE,ACCWORKTIMES,ALARM_0001,ALARM_0002,ALARM_0003,ALARM_0004,...,VEHICLENO,VEHICLESTATUS,VERSIONNUM,WATERTEMPERATURE,WIRELESSTEMP1,WIRELESSTEMP2,WIRELESSTEMP3,WIRELESSTEMP4,WORKDETAILID,WORKHOURS
0,0,535252,NaN,NaN,1.0,1095.83,0.0,0.0,0.0,0.0,...,XUG02631THJE00230,1.0,NaN,NaN,NaN,NaN,NaN,NaN,7285148.0,NaN
1,1,611637,NaN,NaN,1.0,1377.16,0.0,0.0,0.0,0.0,...,XUG02633TGJE00499,1.0,NaN,NaN,NaN,NaN,NaN,NaN,8396881.0,NaN
2,2,176787,NaN,NaN,0.0,261.22,0.0,0.0,0.0,0.0,...,XUG02233HHJE00797,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2172359.0,NaN
3,3,208670,NaN,NaN,1.0,1730.52,0.0,0.0,0.0,0.0,...,XUG02233VHJE01038,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2576101.0,NaN
4,4,450358,NaN,NaN,1.0,0.05,0.0,0.0,0.0,0.0,...,XUG02233CHJE00883,1.0,NaN,NaN,NaN,NaN,NaN,NaN,5953890.0,NaN

In [22]:
columns = []

In [29]:
for i in range(1,11):
    SimpleData = pd.read_csv('./split2/'+str(i)+'_train.csv')
    tempData = SimpleData.dropna(axis=1 , how = 'all').drop(axis=1,)
    columns.append(list(tempData.columns))

D:\software\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (41) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [34]:
dataIndex = columns[1]

In [42]:
SimpleData = pd.read_csv('./split2/9_train.csv')

temp = SimpleData[dataIndex]

In [47]:
temp

,Unnamed: 0,Unnamed: 0.1,ACCRUNTIMES,ACCSTATE,ACCWORKTIMES,ALARM_0001,ALARM_0002,ALARM_0003,ALARM_0004,ALARM_0005,...,SPNMSB2,SPNMSB3,SPNMSB4,SYSTEMDATE,TEMPERATURE,THROTTLECURRENT,UNIQUENO,VEHICLENO,VEHICLESTATUS,WORKDETAILID
0,1600000,1073696,NaN,1.0,7.30,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:40,-40.0,0.0,201803312027587945,XUG03034AJJE01333,1.0,8624913.0
1,1600001,621866,NaN,1.0,1232.77,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:43,NaN,96.0,201703231430035031,XUG02233AHJE01039,1.0,8624929.0
2,1600002,1071257,NaN,1.0,137.37,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:43,NaN,100.0,201703191430034901,XUG02233AHJE00893,1.0,8624930.0
3,1600003,630119,NaN,1.0,580.53,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:44,NaN,90.8,201702031030032060,XUG02633HHJE00354,1.0,8624935.0
4,1600004,630120,NaN,1.0,434.30,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:48,NaN,NaN,201612160830029886,XUG02233KGJE03348,1.0,8624951.0
5,1600005,1071732,NaN,1.0,37.41,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:55,-40.0,36.8,201801312129596188,XUG03034AJJE00327,1.0,8624988.0
6,1600006,628442,NaN,1.0,1327.92,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:57,NaN,26.8,201701061057021452,XUG02633AHJE00027,1.0,8625000.0
7,1600007,622104,NaN,0.0,384.98,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:39:05,NaN,NaN,201703121021324582,XUG02633AHJE00870,0.0,8625053.0
8,1600008,1072062,NaN,1.0,1228.20,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,2018-4-27 8:39:05,NaN,82.8,201704140835245916,XUG02233CHJE01256,1.0,8625048.0
9,1600009,630121,NaN,0.0,413.30,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:51,NaN,NaN,201701251030021982,XUG02233AHJE00294,0.0,8624964.0
10,1600010,622025,NaN,1.0,1251.09,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:55,NaN,91.2,201703200923544923,XUG02233AHJE01171,1.0,8624992.0
11,1600011,200553,1243.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,201704140835245916,NaN,NaN,NaN
12,1600012,200563,1121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,201703301735255403,NaN,NaN,NaN
13,1600013,200562,1121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,201703301735255403,NaN,NaN,NaN
14,1600014,200561,1121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,201703301735255403,NaN,NaN,NaN
15,1600015,1072064,NaN,1.0,1103.98,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,2018-4-27 8:39:50,NaN,100.0,201703301735255403,XUG02233CHJE01166,1.0,8625396.0
16,1600016,628445,NaN,1.0,213.80,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:39:04,NaN,74.0,201702111030022371,XUG02233EHJE00445,1.0,8625044.0
17,1600017,1071893,NaN,1.0,1103.98,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,2018-4-27 8:39:50,NaN,100.0,201703301735255403,XUG02233CHJE01166,1.0,8625389.0
18,1600018,1072063,NaN,1.0,1103.98,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,2018-4-27 8:39:50,NaN,100.0,201703301735255403,XUG02233CHJE01166,1.0,8625393.0
19,1600019,628540,NaN,1.0,1647.66,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:39:35,NaN,100.0,201701201030001846,XUG02633CHJE00204,1.0,8625311.0
20,1600020,628538,NaN,1.0,1647.66,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:39:32,NaN,100.0,201701201030001846,XUG02633CHJE00204,1.0,8625299.0
21,1600021,628539,NaN,1.0,1647.66,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:39:32,NaN,100.0,201701201030001846,XUG02633CHJE00204,1.0,8625300.0
22,1600022,1072228,NaN,1.0,108.79,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,2018-4-27 8:39:05,NaN,74.8,201704140835245904,XUG02233PHJE01244,1.0,8625062.0
23,1600023,1071565,NaN,1.0,414.99,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:55,-40.0,0.0,201705151007377433,XUG03034THJE01852,1.0,8624978.0
24,1600024,1071566,NaN,1.0,55.81,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,2018-4-27 8:38:55,-40.0,93.6,201804021927508004,XUG02633AJJE01538,1.0,8624980.0
25,1600025,200554,672.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,201704140835245904,NaN,NaN,NaN
26,1600026,1072226,NaN,1.0,688.64,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:39:05,NaN,97.2,201705272357138269,XUG02633CHJE02244,1.0,8625057.0
27,1600027,628443,NaN,0.0,2594.49,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:39:00,NaN,NaN,201506300900017238,XUG02633CFJE01687,0.0,8625015.0
28,1600028,1071890,NaN,1.0,17.53,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:59,-40.0,47.2,201802281030006874,XUG03034VJJE00925,1.0,8625013.0
29,1600029,1071734,NaN,1.0,3604.03,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-27 8:38:59,-40.0,0.0,201706130830038670,XUG02633CHJE02423,1.0,8625007.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199970,1799970,697596,NaN,1.0,445.28,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:43:53,NaN,100.0,201701201030011855,XUG02633VHJE00219,1.0,9738619.0
199971,1799971,696792,NaN,1.0,143.80,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:43:38,NaN,100.0,201601231030021592,XUG02233LGJE00246,1.0,9738508.0
199972,1799972,1209725,NaN,1.0,127.44,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:43:38,-40.0,0.0,201803281328137786,XUG03034KJJE01309,1.0,9738549.0
199973,1799973,697746,NaN,0.0,1248.76,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:43:58,NaN,0.0,201703231430035031,XUG02233AHJE01039,0.0,9738632.0
199974,1799974,696987,NaN,1.0,1733.94,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:52:30,NaN,80.0,201703191430034904,XUG02633CHJE00963,1.0,9741953.0
199975,1799975,697745,NaN,1.0,651.50,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:43:54,NaN,100.0,201703211830024988,XUG03034CHJE00991,1.0,9738630.0
199976,1799976,697744,NaN,1.0,545.90,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:43:54,NaN,100.0,201701251030021986,XUG02233CHJE00298,1.0,9738629.0
199977,1799977,1210055,NaN,1.0,42.90,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:43:45,-40.0,92.0,201802272029596869,XUG03034PJJE00921,1.0,9738597.0
199978,1799978,1210665,NaN,1.0,810.77,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:01,NaN,84.0,201704150830046015,XUG02233CHJE01281,1.0,9738684.0
199979,1799979,1210202,NaN,0.0,180.83,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:43:48,-40.0,0.0,201711151030004006,XUG03034VHJE04676,0.0,9738602.0
199980,1799980,698048,NaN,1.0,237.40,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:03,NaN,99.2,201701231130011934,XUG02233LHJE00278,1.0,9738686.0
199981,1799981,1210509,NaN,1.0,157.07,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,2018-4-29 18:44:01,NaN,100.0,201703191430034901,XUG02233AHJE00893,1.0,9738665.0
199982,1799982,175640,285.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,201703191430034901,NaN,NaN,NaN
199983,1799983,697743,NaN,1.0,1238.01,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:43:54,NaN,0.0,201701061057021458,XUG02633PHJE00036,1.0,9738626.0
199984,1799984,697901,NaN,1.0,670.68,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:00,NaN,44.8,201701131530071699,XUG02233HHJE00119,1.0,9738653.0
199985,1799985,698049,NaN,1.0,1557.84,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:03,NaN,NaN,201701251800011999,XUG03034CHJE00313,1.0,9738687.0
199986,1799986,697597,NaN,1.0,572.56,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:43:53,NaN,NaN,201612160930019893,XUG02233CGJE03353,1.0,9738620.0
199987,1799987,1210376,NaN,1.0,662.07,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,2018-4-29 18:43:58,-40.0,78.4,201709221130472782,XUG02233PHJE03902,1.0,9738635.0
199988,1799988,1210505,NaN,0.0,420.88,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:43:58,NaN,NaN,201705151007377433,XUG03034THJE01852,0.0,9738645.0
199989,1799989,1210662,NaN,0.0,365.37,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:01,NaN,NaN,201708101830001241,XUG02634AHJE03180,0.0,9738671.0
199990,1799990,698047,NaN,1.0,813.78,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:01,NaN,0.0,201703200923554931,XUG02633CHJE00969,1.0,9738674.0
199991,1799991,695868,NaN,1.0,1031.10,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:09,NaN,92.8,201702031030022055,XUG02633AHJE00349,1.0,9738725.0
199992,1799992,1210506,NaN,1.0,161.50,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,2018-4-29 18:43:58,-40.0,97.6,201801261730005948,XUG02633KJJE00240,1.0,9738647.0
199993,1799993,1210666,NaN,0.0,14.73,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:01,NaN,NaN,201803312027587945,XUG03034AJJE01333,0.0,9738685.0
199994,1799994,696022,NaN,1.0,49.16,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:14,NaN,100.0,201703041130013902,XUG02633KHJE00636,1.0,9738752.0
199995,1799995,714555,NaN,1.0,942.97,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-30 7:24:49,NaN,0.4,201607071630035781,XUG02633CGJE01697,1.0,9852235.0
199996,1799996,1210796,NaN,0.0,0.30,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:05,NaN,NaN,201804231226228643,XUG03034HJJE01710,0.0,9738701.0
199997,1799997,696163,NaN,1.0,1788.37,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:17,NaN,100.0,201703231430025030,XUG02233VHJE01038,1.0,9738772.0
199998,1799998,1208826,NaN,1.0,979.34,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:17,NaN,41.2,201704180930016164,XUG02634THJE01453,1.0,9738775.0
199999,1799999,698195,NaN,0.0,299.96,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,2018-4-29 18:44:06,NaN,NaN,201601231030021589,XUG02233CGJE00243,0.0,9738710.0

In [53]:

for i in range(1,11):
    SimpleData = pd.read_csv('./split2/'+str(i)+'_train.csv')[dataIndex]
    SimpleData.to_csv('./train_new/'+str(i)+'_train.csv')

D:\software\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (41) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [59]:
labelInfo = pd.read_csv('./train/dbd_faultcode.csv')[['CODE','SPN','FMI']]

In [60]:
labelInfo

     CODE     SPN  FMI
0    1175    1576    5
1    1176    9781   12
2    1177    4232   12
3    1178    4710   12
4    1179     147   12
5    1180    4233    2
6    1181     136    2
7    1182    4641    2
8    1183    1543    2
9    1184    1542    2
10   1185    1537    2
11   1186     822   12
12   1187     823   12
13   1188     834   12
14   1189     833   12
15   1190     901   12
16   1191    1283    8
17   1192    1282    8
18   1193    1281   12
19   1194    1559    3
20   1195    5424   12
21   1196    5477    2
22   1197    2128    2
23   1198    1796    2
24   1199    5750    4
25   1200    5751    3
26   1201    1670   12
27   1202     537   12
28   1203     535   16
29   1204    1316   17
..    ...     ...  ...
443  1439     100   18
444  1440     175   15
445  1441     175    3
446  1442     175    4
447  1444  523470   21
448  1445  520241   11
449  1446  520241   14
450  1447  520241    0
451  1448     157   15
452  1449     157   17
453  1450     157    3
454  1452     157    4
455  1454  520243   16
456  1455  520243    7
457  1456  520243    5
458  1457  520243    0
459  1458  520243    1
460  1459  520243   20
461  1460  520243   21
462  1461  520243   18
463  1462  520243   23
464  1463  520243   24
465  1464  520277    3
466  1465  520277    4
467  1466  520278    3
468  1467  520278    4
469  1468    3509    3
470  1469    3509    4
471  1470    3510    3
472  1471    3510    4

[473 rows x 3 columns]

In [61]:
SimpleData = pd.read_csv('./train_new/1_train.csv')

D:\software\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [62]:
# label 
pd.merge(SimpleData,labelInfo,how='left',on=['FMI','SPN'])

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,ACCRUNTIMES,ACCSTATE,ACCWORKTIMES,ALARM_0001,ALARM_0002,ALARM_0003,ALARM_0004,...,SPNMSB3,SPNMSB4,SYSTEMDATE,TEMPERATURE,THROTTLECURRENT,UNIQUENO,VEHICLENO,VEHICLESTATUS,WORKDETAILID,CODE
0,0,0,535252,NaN,1.0,1095.83,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-23 12:01:05,NaN,0.0,201701231030031930,XUG02631THJE00230,1.0,7285148.0,NaN
1,1,1,611637,NaN,1.0,1377.16,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-26 15:22:06,NaN,NaN,201603011630312344,XUG02633TGJE00499,1.0,8396881.0,NaN
2,2,2,176787,NaN,0.0,261.22,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-8 7:53:52,NaN,0.0,201703061730024203,XUG02233HHJE00797,0.0,2172359.0,NaN
3,3,3,208670,NaN,1.0,1730.52,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-9 9:20:50,NaN,100.0,201703231430025030,XUG02233VHJE01038,1.0,2576101.0,NaN
4,4,4,450358,NaN,1.0,0.05,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-19 5:34:47,NaN,0.0,201703191430034909,XUG02233CHJE00883,1.0,5953890.0,NaN
5,5,5,92034,NaN,1.0,1147.84,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 11:17:39,NaN,0.0,201702201730023064,XUG02233AHJE00568,1.0,1095349.0,NaN
6,6,6,90717,NaN,1.0,673.43,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 10:39:36,NaN,0.0,201702251130053442,XUG02633THJE00620,1.0,1079110.0,NaN
7,7,7,90581,NaN,1.0,0.05,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 10:39:29,NaN,0.0,201703191430034909,XUG02233CHJE00883,1.0,1079007.0,NaN
8,8,8,89939,NaN,1.0,398.32,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 10:08:18,NaN,0.0,201701251030021985,XUG02233EHJE00297,1.0,1064623.0,NaN
9,9,9,89319,NaN,1.0,506.26,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 9:53:55,NaN,NaN,201701131102051669,XUG01633PHJE00086,1.0,1058793.0,NaN
10,10,10,303124,NaN,1.0,1202.23,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-12 14:22:46,NaN,0.0,201702201730023064,XUG02233AHJE00568,1.0,3877173.0,NaN
11,11,11,303306,NaN,1.0,1878.72,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-12 10:55:50,NaN,6.0,201702081330022189,XUG02633LHJE00417,1.0,3813055.0,NaN
12,12,12,88805,NaN,1.0,259.25,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 9:50:23,NaN,0.0,201702150930022668,XUG02033PHJE00504,1.0,1057316.0,NaN
13,13,13,88135,NaN,1.0,673.39,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 9:36:10,NaN,20.4,201702251130053442,XUG02633THJE00620,1.0,1052043.0,NaN
14,14,14,87618,NaN,1.0,1196.48,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 8:57:03,NaN,0.0,201701251030021984,XUG02233HHJE00296,1.0,1041814.0,NaN
15,15,15,303595,NaN,1.0,270.23,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-12 11:04:04,NaN,0.0,201702150930022668,XUG02033PHJE00504,1.0,3816497.0,NaN
16,16,16,508753,NaN,1.0,564.98,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-21 13:12:00,NaN,NaN,201701131102051669,XUG01633PHJE00086,1.0,6914420.0,NaN
17,17,17,84817,NaN,1.0,235.91,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 6:52:09,NaN,0.0,201701061100251460,XUG02633LHJE00045,1.0,1008146.0,NaN
18,18,18,83936,NaN,1.0,1844.09,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 2:29:47,NaN,0.0,201702081330022189,XUG02633LHJE00417,1.0,985938.0,NaN
19,19,19,83287,NaN,1.0,1843.77,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 1:40:46,NaN,8.8,201702081330022189,XUG02633LHJE00417,1.0,982342.0,NaN
20,20,20,82653,NaN,1.0,1843.03,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 0:12:21,NaN,0.0,201702081330022189,XUG02633LHJE00417,1.0,976083.0,NaN
21,21,21,81860,NaN,1.0,1842.38,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-3 22:06:55,NaN,0.0,201702081330022189,XUG02633LHJE00417,1.0,964299.0,NaN
22,22,22,301633,NaN,1.0,523.55,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-12 16:16:44,NaN,NaN,201701131102051669,XUG01633PHJE00086,1.0,3925653.0,NaN
23,23,23,93549,NaN,1.0,956.33,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 12:43:31,NaN,0.0,201702150930022665,XUG02033THJE00503,1.0,1117888.0,NaN
24,24,24,511880,NaN,1.0,711.60,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-21 8:24:34,NaN,34.4,201702251130053442,XUG02633THJE00620,1.0,6812554.0,NaN
25,25,25,81368,NaN,1.0,1841.59,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-3 20:51:44,NaN,0.0,201702081330022189,XUG02633LHJE00417,1.0,952749.0,NaN
26,26,26,100494,NaN,1.0,507.94,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 16:06:49,NaN,NaN,201701131102051669,XUG01633PHJE00086,1.0,1190028.0,NaN
27,27,27,100189,NaN,1.0,1845.91,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 16:16:55,NaN,0.0,201702081330022189,XUG02633LHJE00417,1.0,1194137.0,NaN
28,28,28,514536,NaN,1.0,479.86,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-21 13:29:09,NaN,0.0,201612191330029978,XUG03034EGJE03371,1.0,6919962.0,NaN
29,29,29,514125,NaN,1.0,0.05,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-21 13:24:28,NaN,0.0,201703191430034909,XUG02233CHJE00883,1.0,6918406.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199970,199970,199970,7687,866.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,201707010829589124,NaN,NaN,NaN,1206.0
199971,199971,199971,85475,NaN,0.0,1152.87,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:40:25,NaN,0.0,201703141823594767,XUG02233LHJE00958,0.0,1017114.0,NaN
199972,199972,199972,123041,NaN,1.0,729.61,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:36:51,NaN,85.6,201703300830025363,XUG02233THJE01145,1.0,1016337.0,NaN
199973,199973,199973,123091,NaN,1.0,1072.98,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:36:54,NaN,88.0,201703080930054279,XUG02233KHJE00824,1.0,1016356.0,NaN
199974,199974,199974,7688,1079.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,201703080930054279,NaN,NaN,NaN,1206.0
199975,199975,199975,123092,NaN,1.0,1061.87,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:36:54,-40.0,100.0,201705201829567745,XUG02633LHJE02054,1.0,1016359.0,NaN
199976,199976,199976,123128,NaN,1.0,155.30,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:36:57,-40.0,64.0,201712060929594434,XUG02231CHJE04740,1.0,1016380.0,NaN
199977,199977,199977,123218,NaN,1.0,512.30,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:10,NaN,100.0,201705061530016978,XUG02633LHJE01826,1.0,1016419.0,NaN
199978,199978,199978,85472,NaN,1.0,985.90,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:07,NaN,5.2,201703080930054276,XUG02233CHJE00821,1.0,1016408.0,NaN
199979,199979,199979,123178,NaN,1.0,192.68,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:01,-40.0,0.0,201708101830001246,XUG02634HHJE03179,1.0,1016403.0,NaN
199980,199980,199980,123179,NaN,1.0,416.61,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:07,-40.0,92.0,201707301230009849,XUG02233VHJE03128,1.0,1016409.0,NaN
199981,199981,199981,85510,NaN,1.0,250.99,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:19,NaN,0.0,201703041130013904,XUG02633JHJE00640,1.0,1016455.0,NaN
199982,199982,199982,85521,NaN,1.0,1010.54,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:19,NaN,94.8,201702251130053446,XUG02633CHJE00624,1.0,1016464.0,NaN
199983,199983,199983,85487,NaN,0.0,1152.87,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:13,NaN,NaN,201703141823594767,XUG02233LHJE00958,0.0,1016424.0,NaN
199984,199984,199984,7689,792.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,201704131442275871,NaN,NaN,NaN,1206.0
199985,199985,199985,123219,NaN,1.0,615.73,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:16,-40.0,52.0,201705271430028241,XUG03034THJE02144,1.0,1016434.0,NaN
199986,199986,199986,85546,NaN,1.0,1474.17,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:29,NaN,0.0,201703080930044268,XUG02233VHJE00813,1.0,1016504.0,NaN
199987,199987,199987,123350,NaN,1.0,69.58,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:26,NaN,86.0,201704140835245904,XUG02233PHJE01244,1.0,1016483.0,NaN
199988,199988,199988,85531,NaN,1.0,236.67,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:26,NaN,NaN,201701061100251460,XUG02633LHJE00045,1.0,1016484.0,NaN
199989,199989,199989,7691,1331.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,201703301130045382,NaN,NaN,NaN,1206.0
199990,199990,199990,123399,NaN,1.0,1317.67,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:32,NaN,0.0,201703301130045382,XUG03034THJE01057,1.0,1016524.0,NaN
199991,199991,199991,7690,739.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,201704180930016169,NaN,NaN,NaN,1206.0
199992,199992,199992,123395,NaN,1.0,725.28,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:29,NaN,0.0,201704180930016169,XUG02633THJE01458,1.0,1016502.0,NaN
199993,199993,199993,85556,NaN,1.0,1002.67,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:36,NaN,93.2,201702081330022194,XUG02633EHJE00422,1.0,1016543.0,NaN
199994,199994,199994,85584,NaN,1.0,1178.53,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:48,NaN,80.0,201703200923544923,XUG02233AHJE01171,1.0,1016575.0,NaN
199995,199995,199995,123398,NaN,0.0,8.14,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:32,NaN,NaN,201705191429587670,XUG02634PHJE01776,0.0,1016518.0,NaN
199996,199996,199996,123396,NaN,0.0,177.26,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:29,NaN,NaN,201710241459583443,XUG03034CHJE04331,0.0,1016507.0,NaN
199997,199997,199997,85668,NaN,1.0,1619.48,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:34:10,NaN,32.0,201609050830036980,XUG02233CGJE02275,1.0,1015329.0,NaN
199998,199998,199998,85685,NaN,1.0,1451.45,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:35:31,NaN,84.0,201701201030011854,XUG02633CHJE00218,1.0,1015833.0,NaN
199999,199999,199999,123435,NaN,1.0,643.55,0.0,0.0,0.0,0.0,...,NaN,NaN,2018-4-4 7:37:35,NaN,64.0,201704140835245903,XUG02233THJE01243,1.0,1016534.0,NaN

In [63]:
for i in range(1,11):
    SimpleData = pd.read_csv('./split2/'+str(i)+'_train.csv')[dataIndex]
    tempData = pd.merge(SimpleData,labelInfo,how='left',on =['FMI','SPN'])
    tempData.to_csv('./train_x/'+str(i)+'_train.csv')

D:\software\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (41) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [64]:
SimpleData = pd.read_csv('./train_x/1_train.csv')

D:\software\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [69]:
SimpleData = SimpleData[np.isnan(SimpleData['CODE'])==False]

          CODE
23150   1206.0
23178   1206.0
23208   1206.0
23240   1206.0
23274   1206.0
23306   1206.0
23308   1206.0
23319   1206.0
23338   1206.0
23339   1206.0
23356   1206.0
23370   1206.0
23391   1206.0
23406   1206.0
23408   1206.0
23426   1206.0
23441   1206.0
23444   1206.0
23447   1206.0
23463   1206.0
23479   1206.0
23513   1206.0
23517   1206.0
23543   1206.0
23549   1206.0
23555   1206.0
23565   1206.0
23586   1206.0
23592   1206.0
23603   1206.0
...        ...
199806  1206.0
199810  1206.0
199827  1206.0
199829  1206.0
199836  1206.0
199841  1206.0
199847  1206.0
199852  1206.0
199865  1206.0
199870  1206.0
199871  1206.0
199875  1206.0
199876  1206.0
199889  1206.0
199892  1206.0
199904  1206.0
199908  1206.0
199912  1206.0
199919  1206.0
199928  1206.0
199931  1206.0
199938  1206.0
199942  1206.0
199946  1206.0
199949  1206.0
199970  1206.0
199974  1206.0
199984  1206.0
199989  1206.0
199991  1206.0

[21741 rows x 1 columns]

In [72]:
## get real train data


for i in range(1,11):
    SimpleData = pd.read_csv('./train_x/'+str(i)+'_train.csv')
    SimpleData = SimpleData[np.isnan(SimpleData['CODE'])==False]
    SimpleData.to_csv('./train_5/'+str(i)+'_train.csv')

D:\software\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [73]:
##contract dataframe
SimpleData_1 = pd.read_csv('./train_5/'+str(i)+'_train.csv')
SimpleData_2 = pd.read_csv('./train_5/'+str(i)+'_train.csv')
SimpleData_3 = pd.read_csv('./train_5/'+str(i)+'_train.csv')
SimpleData_4 = pd.read_csv('./train_5/'+str(i)+'_train.csv')
SimpleData_5 = pd.read_csv('./train_5/'+str(i)+'_train.csv')
SimpleData_6 = pd.read_csv('./train_5/'+str(i)+'_train.csv')
SimpleData_7 = pd.read_csv('./train_5/'+str(i)+'_train.csv')
SimpleData_8 = pd.read_csv('./train_5/'+str(i)+'_train.csv')
SimpleData_9 = pd.read_csv('./train_5/'+str(i)+'_train.csv')
SimpleData_10 = pd.read_csv('./train_5/'+str(i)+'_train.csv')

dfs = [SimpleData_1 ,SimpleData_2 ,SimpleData_3,SimpleData_4,SimpleData_5,SimpleData_6,SimpleData_7,SimpleData_8,SimpleData_9,SimpleData_10]

In [74]:
temp_train = pd.concat(dfs)

In [76]:
temp_train.dropna(axis=1,how='all')

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,ACCRUNTIMES,AREA,CITY,COLLECTTIME,FAULTTIME,FMI,FRID,LAT,LNG,PROVINCE,READFLAG,SPN,UNIQUENO,CODE
0,6,6,1800006,175641,866.0,510183.0,510100.0,2018-04-29 18:45:15,2018-04-29 18:45:15,15.0,2627069.0,30.351392,30.351392,510000.0,1.0,8809.0,201703042130053982,1206.0
1,19,19,1800019,175642,1127.0,341322.0,341300.0,2018-04-29 18:45:29,2018-04-29 18:45:29,15.0,2627070.0,34.107017,34.107017,340000.0,1.0,8809.0,201704140835245913,1206.0
2,31,31,1800031,175649,663.0,410122.0,410100.0,2018-04-29 18:45:46,2018-04-29 18:45:46,15.0,2627078.0,34.869911,34.869911,410000.0,1.0,8809.0,201704071712265675,1206.0
3,35,35,1800035,175645,663.0,410122.0,410100.0,2018-04-29 18:45:46,2018-04-29 18:45:46,15.0,2627073.0,34.869911,34.869911,410000.0,1.0,8809.0,201704071712265675,1206.0
4,48,48,1800048,175643,1137.0,320829.0,320800.0,2018-04-29 18:45:52,2018-04-29 18:45:52,15.0,2627071.0,33.282495,33.282495,320000.0,1.0,8809.0,201703301735255408,1206.0
5,49,49,1800049,175646,1813.0,500106.0,500100.0,2018-04-29 18:45:52,2018-04-29 18:45:52,15.0,2627074.0,29.568729,29.568729,500000.0,1.0,8809.0,201703271030015170,1206.0
6,62,62,1800062,175652,1097.0,410522.0,410500.0,2018-04-29 18:46:03,2018-04-29 18:46:03,15.0,2627081.0,36.194851,36.194851,410000.0,1.0,8809.0,201703101812034562,1206.0
7,71,71,1800071,175648,901.0,653222.0,653200.0,2018-04-29 18:46:06,2018-04-29 18:46:06,15.0,2627077.0,37.191906,37.191906,650000.0,1.0,8809.0,201708201530051558,1206.0
8,72,72,1800072,175647,695.0,370725.0,370700.0,2018-04-29 18:46:06,2018-04-29 18:46:06,15.0,2627075.0,36.512629,36.512629,370000.0,1.0,8809.0,201705101530077175,1206.0
9,77,77,1800077,175650,4329.0,150622.0,150600.0,2018-04-29 18:46:11,2018-04-29 18:46:11,4.0,2627079.0,39.592567,39.592567,150000.0,1.0,108.0,201704241116166406,1239.0
10,91,91,1800091,175653,546.0,371722.0,371700.0,2018-04-29 18:46:23,2018-04-29 18:46:23,15.0,2627083.0,34.679507,34.679507,370000.0,1.0,8809.0,201706071000188530,1206.0
11,94,94,1800094,175654,289.0,340521.0,340500.0,2018-04-29 18:46:25,2018-04-29 18:46:25,15.0,2627084.0,31.552484,31.552484,340000.0,1.0,8809.0,201702211030013081,1206.0
12,117,117,1800117,175655,285.0,371523.0,371500.0,2018-04-29 18:46:52,2018-04-29 18:46:52,15.0,2627085.0,36.595941,36.595941,370000.0,1.0,8809.0,201703191430034901,1206.0
13,131,131,1800131,175656,866.0,510183.0,510100.0,2018-04-29 18:47:08,2018-04-29 18:47:08,15.0,2627087.0,30.351476,30.351476,510000.0,1.0,8809.0,201703042130053982,1206.0
14,147,147,1800147,175657,1127.0,341322.0,341300.0,2018-04-29 18:47:27,2018-04-29 18:47:27,15.0,2627088.0,34.107382,34.107382,340000.0,1.0,8809.0,201704140835245913,1206.0
15,152,152,1800152,175658,546.0,371722.0,371700.0,2018-04-29 18:47:35,2018-04-29 18:47:35,15.0,2627089.0,34.679505,34.679505,370000.0,1.0,8809.0,201706071000188530,1206.0
16,159,159,1800159,175660,1137.0,320829.0,320800.0,2018-04-29 18:47:39,2018-04-29 18:47:39,15.0,2627091.0,33.282539,33.282539,320000.0,1.0,8809.0,201703301735255408,1206.0
17,165,165,1800165,175662,663.0,410122.0,410100.0,2018-04-29 18:47:47,2018-04-29 18:47:47,15.0,2627093.0,34.869786,34.869786,410000.0,1.0,8809.0,201704071712265675,1206.0
18,172,172,1800172,175664,695.0,370725.0,370700.0,2018-04-29 18:47:53,2018-04-29 18:47:53,15.0,2627095.0,36.512386,36.512386,370000.0,1.0,8809.0,201705101530077175,1206.0
19,190,190,1800190,175663,901.0,653222.0,653200.0,2018-04-29 18:48:06,2018-04-29 18:48:06,15.0,2627094.0,37.191895,37.191895,650000.0,1.0,8809.0,201708201530051558,1206.0
20,197,197,1800197,176813,1097.0,410522.0,410500.0,2018-04-29 18:48:11,2018-04-29 18:48:11,15.0,2627097.0,36.194568,36.194568,410000.0,1.0,8809.0,201703101812034562,1206.0
21,202,202,1800202,176812,4329.0,150622.0,150600.0,2018-04-29 18:48:13,2018-04-29 18:48:13,4.0,2627096.0,39.591039,39.591039,150000.0,1.0,108.0,201704241116166406,1239.0
22,215,215,1800215,176814,289.0,340521.0,340500.0,2018-04-29 18:48:26,2018-04-29 18:48:26,15.0,2627098.0,31.552522,31.552522,340000.0,1.0,8809.0,201702211030013081,1206.0
23,239,239,1800239,176815,285.0,371523.0,371500.0,2018-04-29 18:48:52,2018-04-29 18:48:52,15.0,2627100.0,36.596028,36.596028,370000.0,1.0,8809.0,201703191430034901,1206.0
24,260,260,1800260,176817,866.0,510183.0,510100.0,2018-04-29 18:49:20,2018-04-29 18:49:20,15.0,2627102.0,30.351277,30.351277,510000.0,1.0,8809.0,201703042130053982,1206.0
25,268,268,1800268,176818,1127.0,341322.0,341300.0,2018-04-29 18:49:25,2018-04-29 18:49:25,15.0,2627103.0,34.107291,34.107291,340000.0,1.0,8809.0,201704140835245913,1206.0
26,279,279,1800279,176820,1137.0,320829.0,320800.0,2018-04-29 18:49:40,2018-04-29 18:49:40,15.0,2627105.0,33.282605,33.282605,320000.0,1.0,8809.0,201703301735255408,1206.0
27,285,285,1800285,176821,663.0,410122.0,410100.0,2018-04-29 18:49:47,2018-04-29 18:49:47,15.0,2627107.0,34.869978,34.869978,410000.0,1.0,8809.0,201704071712265675,1206.0
28,287,287,1800287,176824,663.0,410122.0,410100.0,2018-04-29 18:49:47,2018-04-29 18:49:47,15.0,2627110.0,34.869978,34.869978,410000.0,1.0,8809.0,201704071712265675,1206.0
29,295,295,1800295,176822,695.0,370725.0,370700.0,2018-04-29 18:49:55,2018-04-29 18:49:55,15.0,2627108.0,36.512657,36.512657,370000.0,1.0,8809.0,201705101530077175,1206.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9507,74602,74602,1874602,235583,4355.0,150622.0,150600.0,2018-04-30 23:20:18,2018-04-30 23:20:18,4.0,2638796.0,39.589049,39.589049,150000.0,1.0,108.0,201704241116166406,1239.0
9508,74613,74613,1874613,235584,1322.0,330211.0,330200.0,2018-04-30 23:21:18,2018-04-30 23:21:18,15.0,2638797.0,29.953716,29.953716,330000.0,1.0,8809.0,201705061530026982,1206.0
9509,74619,74619,1874619,235585,879.0,510183.0,510100.0,2018-04-30 23:21:53,2018-04-30 23:21:53,15.0,2638798.0,30.352847,30.352847,510000.0,1.0,8809.0,201703042130053982,1206.0
9510,74626,74626,1874626,235586,4355.0,150622.0,150600.0,2018-04-30 23:22:15,2018-04-30 23:22:15,4.0,2638799.0,39.589055,39.589055,150000.0,1.0,108.0,201704241116166406,1239.0
9511,74631,74631,1874631,235587,904.0,653222.0,653200.0,2018-04-30 23:22:59,2018-04-30 23:22:59,15.0,2638800.0,37.190535,37.190535,650000.0,1.0,8809.0,201708201530051558,1206.0
9512,74637,74637,1874637,235588,1322.0,330211.0,330200.0,2018-04-30 23:23:16,2018-04-30 23:23:16,15.0,2638801.0,29.953714,29.953714,330000.0,1.0,8809.0,201705061530026982,1206.0
9513,74647,74647,1874647,235589,879.0,510183.0,510100.0,2018-04-30 23:24:01,2018-04-30 23:24:01,15.0,2638802.0,30.353064,30.353064,510000.0,1.0,8809.0,201703042130053982,1206.0
9514,74652,74652,1874652,235590,4355.0,150622.0,150600.0,2018-04-30 23:24:27,2018-04-30 23:24:27,4.0,2638803.0,39.589054,39.589054,150000.0,1.0,108.0,201704241116166406,1239.0
9515,74660,74660,1874660,235591,4355.0,150622.0,150600.0,2018-04-30 23:25:11,2018-04-30 23:25:11,4.0,2638804.0,39.589058,39.589058,150000.0,1.0,108.0,201704241116166406,1239.0
9516,74662,74662,1874662,235592,1322.0,330211.0,330200.0,2018-04-30 23:25:13,2018-04-30 23:25:13,15.0,2638805.0,29.953714,29.953714,330000.0,1.0,8809.0,201705061530026982,1206.0
9517,74673,74673,1874673,235593,879.0,510183.0,510100.0,2018-04-30 23:25:54,2018-04-30 23:25:54,15.0,2638806.0,30.353072,30.353072,510000.0,1.0,8809.0,201703042130053982,1206.0
9518,74687,74687,1874687,235594,1322.0,330211.0,330200.0,2018-04-30 23:27:11,2018-04-30 23:27:11,15.0,2638807.0,29.953723,29.953723,330000.0,1.0,8809.0,201705061530026982,1206.0
9519,74702,74702,1874702,235595,879.0,510183.0,510100.0,2018-04-30 23:28:02,2018-04-30 23:28:02,15.0,2638808.0,30.353250,30.353250,510000.0,1.0,8809.0,201703042130053982,1206.0
9520,74706,74706,1874706,235596,1322.0,330211.0,330200.0,2018-04-30 23:28:05,2018-04-30 23:28:05,15.0,2638809.0,29.953868,29.953868,330000.0,1.0,8809.0,201705061530026982,1206.0
9521,74737,74737,1874737,235597,879.0,510183.0,510100.0,2018-04-30 23:29:54,2018-04-30 23:29:54,15.0,2638810.0,30.353653,30.353653,510000.0,1.0,8809.0,201703042130053982,1206.0
9522,74743,74743,1874743,235598,879.0,510183.0,510100.0,2018-04-30 23:30:37,2018-04-30 23:30:37,15.0,2638811.0,30.353787,30.353787,510000.0,1.0,8809.0,201703042130053982,1206.0
9523,74833,74833,1874833,235600,4355.0,150622.0,150600.0,2018-04-30 23:38:17,2018-04-30 23:38:17,4.0,2638814.0,39.589062,39.589062,150000.0,1.0,108.0,201704241116166406,1239.0
9524,74851,74851,1874851,235599,4355.0,150622.0,150600.0,2018-04-30 23:40:08,2018-04-30 23:40:08,4.0,2638813.0,39.588759,39.588759,150000.0,1.0,108.0,201704241116166406,1239.0
9525,74876,74876,1874876,235601,4355.0,150622.0,150600.0,2018-04-30 23:42:04,2018-04-30 23:42:04,4.0,2638815.0,39.588349,39.588349,150000.0,1.0,108.0,201704241116166406,1239.0
9526,74888,74888,1874888,235602,4355.0,150622.0,150600.0,2018-04-30 23:43:59,2018-04-30 23:43:59,4.0,2638816.0,39.588353,39.588353,150000.0,1.0,108.0,201704241116166406,1239.0
9527,74911,74911,1874911,235603,4355.0,150622.0,150600.0,2018-04-30 23:46:00,2018-04-30 23:46:00,4.0,2638817.0,39.588462,39.588462,150000.0,1.0,108.0,201704241116166406,1239.0
9528,74934,74934,1874934,235606,4355.0,150622.0,150600.0,2018-04-30 23:48:02,2018-04-30 23:48:02,4.0,2638820.0,39.588283,39.588283,150000.0,1.0,108.0,201704241116166406,1239.0
9529,74957,74957,1874957,235609,4355.0,150622.0,150600.0,2018-04-30 23:50:04,2018-04-30 23:50:04,4.0,2638823.0,39.588397,39.588397,150000.0,1.0,108.0,201704241116166406,1239.0
9530,74988,74988,1874988,235610,4355.0,150622.0,150600.0,2018-04-30 23:52:07,2018-04-30 23:52:07,4.0,2638824.0,39.588221,39.588221,150000.0,1.0,108.0,201704241116166406,1239.0
9531,75005,75005,1875005,235611,4355.0,150622.0,150600.0,2018-04-30 23:53:55,2018-04-30 23:53:55,4.0,2638825.0,39.588322,39.588322,150000.0,1.0,108.0,201704241116166406,1239.0
9532,75014,75014,1875014,235612,635.0,220105.0,220100.0,2018-04-30 23:54:45,2018-04-30 23:54:45,15.0,2638826.0,43.975841,43.975841,220000.0,1.0,8809.0,201703231430035032,1206.0
9533,75032,75032,1875032,235613,4355.0,150622.0,150600.0,2018-04-30 23:55:57,2018-04-30 23:55:57,4.0,2638827.0,39.588411,39.588411,150000.0,1.0,108.0,201704241116166406,1239.0
9534,75039,75039,1875039,235614,635.0,220105.0,220100.0,2018-04-30 23:56:44,2018-04-30 23:56:44,15.0,2638828.0,43.975986,43.975986,220000.0,1.0,8809.0,201703231430035032,1206.0
9535,75047,75047,1875047,235615,635.0,220105.0,220100.0,2018-04-30 23:57:05,2018-04-30 23:57:05,15.0,2638829.0,43.976038,43.976038,220000.0,1.0,8809.0,201703231430035032,1206.0
9536,75054,75054,1875054,235616,4355.0,150622.0,150600.0,2018-04-30 23:58:00,2018-04-30 23:58:00,4.0,2638830.0,39.588404,39.588404,150000.0,1.0,108.0,201704241116166406,1239.0

In [77]:
set(temp_train['CODE'])

{1141.0, 1168.0, 1182.0, 1206.0, 1239.0}